import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import { getServerSession } from 'next-auth/next';
import { authConfig } from '@/pages/api/auth/[...nextauth]';
import { Roboto, Lobster_Two, Lobster } from 'next/font/google';
import Hydrate from "./components/Hydrate";
// import { useThemeStore } from "@/store";

//define fonts
const roboto = Roboto({ weight: ['400', '500', '700'], subsets: ['latin'], variable: '--font-roboto' })
const lobster = Lobster({ weight: ['400'], subsets: ['latin'], variable: '--font-lobster' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authConfig);
  // const { mode } = useThemeStore();
  return (
    <html lang="en" className={`${roboto.className} ${lobster.variable}`}>
      <Hydrate>
        <Nav user={session?.user} expires={session?.expires as string} />
        {children}
      </Hydrate>
    </html>
  );
}
